apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ovisb/hello_docker_helm.git
    targetRevision: main
    path: charts/hello-docker
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
