apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
 name: {{ .Release.Name }}
spec:
 provider: azure
 parameters:
   useVMManagedIdentity: "true"
   usePodIdentity: "false"
   userAssignedIdentityID: {{ .Values.clientId | quote }}
   keyvaultName: {{ .Values.vaultName | quote }}
   objects: |  # expose vault secrets defined in values
     array:
       {{- range .Values.secrets }}
       - |
         objectName: {{ . }}
         objectType: secret
         objectVersion: ""
       {{- end }}
   tenantId: {{ .Values.tenantId | quote }}
 secretObjects:  # reflect exposed objects in k8s Secret
   - data:
     {{- range .Values.secrets }}
     - objectName: {{ . }}
       key: {{ . }}
     {{- end }}
     secretName: {{ .Release.Name }}-secret
     type: Opaque